# dev.yml
---
  - name: Dev Environment Setup
    hosts: webserversdev
    become: yes
    tasks:
      - name: Install Apache
        apt:
          name: apache2
          state: present

      - name: Install Node.js
        apt:
          name: nodejs
          state: present

  - name: Database Server Installation
    hosts: dbserversdev
    become: yes
    tasks:
      - name: Install MariaDB
        apt:
          name: mariadb-server
          state: present

  - name: Web Application Deployment
    hosts: webserversdev
    become: yes
    tasks:
      - name: Deploy Web Application from Git
        git:
          repo: "git@github.com:ttu-bburchfield/swollenhippofinal.git"
          dest: "/var/www/html"

